Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'RunOurSqlCommands Edit Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "87fbabf8-c559-4fd4-b921-bc7cc3ccfa55", "278824d6-c5e0-48aa-bc58-7b837be2e519", "Utility")> _
Partial Public Class [RunOurSqlCommandsEditDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _command As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _results As Global.Blackbaud.AppFx.UIModeling.Core.StringField
	Private WithEvents _executesql As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
	Private WithEvents _columnlist As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _command = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _results = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
		_executesql = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
		_columnlist = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New Guid("87fbabf8-c559-4fd4-b921-bc7cc3ccfa55")
        MyBase.DataFormInstanceId = New Guid("278824d6-c5e0-48aa-bc58-7b837be2e519")
        MyBase.RecordType = "Utility"
		MyBase.FixedDialog = False
		MyBase.FORMHEADER.Value = "Run our SQL"
		MyBase.UserInterfaceUrl = "browser/htmlforms/custom/RunOurSqlCommandsEditDataForm.html"

        '
        '_command
        '
        _command.Name = "COMMAND"
        _command.Caption = "Command"
        Me.Fields.Add(_command)
        '
        '_results
        '
        _results.Name = "RESULTS"
        _results.Caption = "Results"
        Me.Fields.Add(_results)
        '
        '_executesql
        '
        _executesql.Name = "EXECUTESQL"
        _executesql.Caption = "Run"
		Me.Actions.Add(_executesql)
		'
		'_columnlist
		'
		_columnlist.Name = "COLUMNLIST"
		_columnlist.Caption = "Comma-separated list of columns"
		Me.Fields.Add(_columnlist)


		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Command
    ''' </summary>
    <System.ComponentModel.Description("Command")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [COMMAND]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _command
        End Get
    End Property
    
    ''' <summary>
    ''' Results
    ''' </summary>
    <System.ComponentModel.Description("Results")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [RESULTS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _results
        End Get
    End Property
    
    ''' <summary>
    ''' Run
    ''' </summary>
    <System.ComponentModel.Description("Run")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [EXECUTESQL]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _executesql
        End Get
    End Property

	''' <summary>
	''' Columnlist
	''' </summary>
	<System.ComponentModel.Description("Columnlist")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [COLUMNLIST] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
		Get
			Return _columnlist
		End Get
	End Property

End Class
