Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'InteractionExtensionEditFormCHILDREN' data form
''' </summary>
Partial Public Class [InteractionExtensionEditFormCHILDRENUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.UIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _id As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _childlookupid As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _sponsorshipopportunitychildid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _id = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _childlookupid = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _sponsorshipopportunitychildid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)

        '
        '_id
        '
        _id.Name = "ID"
        _id.Caption = "ID"
        _id.Visible = False
        Me.Fields.Add(_id)
        '
        '_childlookupid
        '
        _childlookupid.Name = "CHILDLOOKUPID"
		_childlookupid.Caption = "Child ID"
		_childlookupid.Enabled = False
        Me.Fields.Add(_childlookupid)
        '
        '_sponsorshipopportunitychildid
        '
        _sponsorshipopportunitychildid.Name = "SPONSORSHIPOPPORTUNITYCHILDID"
        _sponsorshipopportunitychildid.Caption = "Child Name"
        _sponsorshipopportunitychildid.SearchListID = New Guid("ab076868-114a-4696-afe9-8d590677708c")
        Me.Fields.Add(_sponsorshipopportunitychildid)

		OnCreated()

    End Sub
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [ID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _id
        End Get
    End Property
    
    ''' <summary>
    ''' Child ID
    ''' </summary>
    <System.ComponentModel.Description("Child ID")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CHILDLOOKUPID]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _childlookupid
        End Get
    End Property
    
    ''' <summary>
    ''' Child Name
    ''' </summary>
    <System.ComponentModel.Description("Child Name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SPONSORSHIPOPPORTUNITYCHILDID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _sponsorshipopportunitychildid
        End Get
    End Property
    
End Class
