Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Update Child Interactions Global Change' data form
''' </summary>

Partial Public Class [UpdateChildInteractionsGlobalChangeUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.CustomUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the OPERATION property
    ''' </summary>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Enum OPERATIONS As Integer
        [Replace] = 2
    End Enum

    ''' <summary>
    ''' Enumerated values for use with the REPLACESTATUSCODEWITHVALUE property
    ''' </summary>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Enum REPLACESTATUSCODEWITHVALUES As Integer
        [Pending] = 1
        [Completed] = 2
        [Canceled] = 4
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _idsetregisterid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _recordtypeid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _operation As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of OPERATIONS))
    Private WithEvents _actualdate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _comment As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _replacestatuscodewithvalue As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of REPLACESTATUSCODEWITHVALUES)

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _idsetregisterid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _recordtypeid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _operation = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of OPERATIONS))
        _actualdate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _comment = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _replacestatuscodewithvalue = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of REPLACESTATUSCODEWITHVALUES)

		MyBase.UserInterfaceUrl = "browser/htmlforms/custom/UpdateChildInteractionsGlobalChange.html"

        '
        '_idsetregisterid
        '
        _idsetregisterid.Name = "IDSETREGISTERID"
        _idsetregisterid.Caption = "Selection"
        _idsetregisterid.Required = True
        _idsetregisterid.SearchListID = New Guid("98d0070e-c4a7-495b-a438-2ac12da79068")
        _idsetregisterid.EnableQuickFind = True
        _idsetregisterid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "RECORDTYPEID", .Caption = "Record type", .ReadOnly = True, .DefaultValueText = "Fields!RECORDTYPEID"})
        _idsetregisterid.SystemSearchType = Global.Blackbaud.AppFx.UIModeling.Core.SystemSearchType.Selection
        Me.Fields.Add(_idsetregisterid)
        '
        '_recordtypeid
        '
        _recordtypeid.Name = "RECORDTYPEID"
        _recordtypeid.Caption = "RECORDTYPEID"
        _recordtypeid.Visible = False
        _recordtypeid.DBReadOnly = True
        Me.Fields.Add(_recordtypeid)
        '
        '_operation
        '
        _operation.Name = "OPERATION"
        _operation.Caption = "Operation"
        _operation.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of OPERATIONS)) With {.Value = OPERATIONS.[Replace], .Translation = "Replace"})
        _operation.Value = OPERATIONS.[Replace]
        Me.Fields.Add(_operation)
        '
        '_actualdate
        '
        _actualdate.Name = "ACTUALDATE"
        _actualdate.Caption = "Actual date"
        Me.Fields.Add(_actualdate)
        '
        '_comment
        '
        _comment.Name = "COMMENT"
        _comment.Caption = "Comment"
        Me.Fields.Add(_comment)
        '
        '_replacestatuscodewithvalue
        '
        _replacestatuscodewithvalue.Name = "REPLACESTATUSCODEWITHVALUE"
        _replacestatuscodewithvalue.Caption = "Replace status code with"
        _replacestatuscodewithvalue.Required = True
        _replacestatuscodewithvalue.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of REPLACESTATUSCODEWITHVALUES) With {.Value = REPLACESTATUSCODEWITHVALUES.[Pending], .Translation = "Pending"})
        _replacestatuscodewithvalue.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of REPLACESTATUSCODEWITHVALUES) With {.Value = REPLACESTATUSCODEWITHVALUES.[Completed], .Translation = "Completed"})
        _replacestatuscodewithvalue.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of REPLACESTATUSCODEWITHVALUES) With {.Value = REPLACESTATUSCODEWITHVALUES.[Canceled], .Translation = "Canceled"})
        Me.Fields.Add(_replacestatuscodewithvalue)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Selection
    ''' </summary>
    <System.ComponentModel.Description("Selection")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [IDSETREGISTERID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _idsetregisterid
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [RECORDTYPEID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _recordtypeid
        End Get
    End Property
    
    ''' <summary>
    ''' Operation
    ''' </summary>
    <System.ComponentModel.Description("Operation")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [OPERATION]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of OPERATIONS))
        Get
            Return _operation
        End Get
    End Property
    
    ''' <summary>
    ''' Actual date
    ''' </summary>
    <System.ComponentModel.Description("Actual date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [ACTUALDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _actualdate
        End Get
    End Property
    
    ''' <summary>
    ''' Comment
    ''' </summary>
    <System.ComponentModel.Description("Comment")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [COMMENT]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _comment
        End Get
    End Property
    
    ''' <summary>
    ''' Replace status code with
    ''' </summary>
    <System.ComponentModel.Description("Replace status code with")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [REPLACESTATUSCODEWITHVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of REPLACESTATUSCODEWITHVALUES)
        Get
            Return _replacestatuscodewithvalue
        End Get
    End Property
    
End Class
