Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Interaction Extension Add Form 2' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "25aa26c5-d2fe-401c-b33d-a6382d932e44", "19cc7e46-2646-4a12-b196-bd840b4f9d9a", "Interaction Extension", "INTERACTION")> _
Partial Public Class [InteractionExtensionAddFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the RESENDCODE property
    ''' </summary>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Enum RESENDCODES As Integer
        [No] = 0
        [Yes] = 1
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _lettertypecodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _letterchildversioncodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _fulfillmentstatuscodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _resendcode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of RESENDCODES))
    Private WithEvents _eftbrochure As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _departedchildid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _unavilablechildid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _doublesponsoredchildid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _transferchildid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _previouschildprojectid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _previousbirthdate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _previousname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _children As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of InteractionExtensionAddFormCHILDRENUIModel)

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _lettertypecodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _letterchildversioncodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _fulfillmentstatuscodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _resendcode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of RESENDCODES))
        _eftbrochure = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _departedchildid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _unavilablechildid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _doublesponsoredchildid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _transferchildid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _previouschildprojectid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _previousbirthdate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _previousname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _children = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of InteractionExtensionAddFormCHILDRENUIModel)

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New Guid("25aa26c5-d2fe-401c-b33d-a6382d932e44")
        MyBase.DataFormInstanceId = New Guid("19cc7e46-2646-4a12-b196-bd840b4f9d9a")
        MyBase.RecordType = "Interaction Extension"
        MyBase.ContextRecordType = "INTERACTION"
        MyBase.FixedDialog = True
        MyBase.ExtensionTabCaption = "Additional Info"
        MyBase.UserInterfaceUrl = "browser/htmlforms/Interactions/InteractionExtension.AddForm.html"

        '
        '_lettertypecodeid
        '
        _lettertypecodeid.Name = "LETTERTYPECODEID"
        _lettertypecodeid.Caption = "Lettertype"
        _lettertypecodeid.CodeTableName = "USR_INTERACTIONEXTENSIONLETTERTYPECODE"
        Me.Fields.Add(_lettertypecodeid)
        '
        '_letterchildversioncodeid
        '
        _letterchildversioncodeid.Name = "LETTERCHILDVERSIONCODEID"
        _letterchildversioncodeid.Caption = "Letterchildversion"
        _letterchildversioncodeid.CodeTableName = "USR_INTERACTIONEXTENSIONLETTERCHILDVERSIONCODE"
        Me.Fields.Add(_letterchildversioncodeid)
        '
        '_fulfillmentstatuscodeid
        '
        _fulfillmentstatuscodeid.Name = "FULFILLMENTSTATUSCODEID"
        _fulfillmentstatuscodeid.Caption = "Fulfillmentstatus"
        _fulfillmentstatuscodeid.CodeTableName = "USR_INTERACTIONEXTENSIONFULFILLMENTSTATUSCODE"
        Me.Fields.Add(_fulfillmentstatuscodeid)
        '
        '_resendcode
        '
        _resendcode.Name = "RESENDCODE"
        _resendcode.Caption = "Resend"
        _resendcode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of RESENDCODES)) With {.Value = RESENDCODES.[No], .Translation = "No"})
        _resendcode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of RESENDCODES)) With {.Value = RESENDCODES.[Yes], .Translation = "Yes"})
        _resendcode.Value = RESENDCODES.[No]
        Me.Fields.Add(_resendcode)
        '
        '_eftbrochure
        '
        _eftbrochure.Name = "EFTBROCHURE"
        _eftbrochure.Caption = "Eftbrochure"
        Me.Fields.Add(_eftbrochure)
        '
        '_departedchildid
        '
        _departedchildid.Name = "DEPARTEDCHILDID"
        _departedchildid.Caption = "Departedchild"
        _departedchildid.SearchListID = New Guid("ab076868-114a-4696-afe9-8d590677708c")
        Me.Fields.Add(_departedchildid)
        '
        '_unavilablechildid
        '
        _unavilablechildid.Name = "UNAVILABLECHILDID"
        _unavilablechildid.Caption = "Unavilablechild"
        _unavilablechildid.SearchListID = New Guid("ab076868-114a-4696-afe9-8d590677708c")
        Me.Fields.Add(_unavilablechildid)
        '
        '_doublesponsoredchildid
        '
        _doublesponsoredchildid.Name = "DOUBLESPONSOREDCHILDID"
        _doublesponsoredchildid.Caption = "Doublesponsoredchild"
        _doublesponsoredchildid.SearchListID = New Guid("ab076868-114a-4696-afe9-8d590677708c")
        Me.Fields.Add(_doublesponsoredchildid)
        '
        '_transferchildid
        '
        _transferchildid.Name = "TRANSFERCHILDID"
        _transferchildid.Caption = "Transferchild"
        _transferchildid.SearchListID = New Guid("ab076868-114a-4696-afe9-8d590677708c")
        Me.Fields.Add(_transferchildid)
        '
        '_previouschildprojectid
        '
        _previouschildprojectid.Name = "PREVIOUSCHILDPROJECTID"
        _previouschildprojectid.Caption = "Previouschildproject"
        Me.Fields.Add(_previouschildprojectid)
        '
        '_previousbirthdate
        '
        _previousbirthdate.Name = "PREVIOUSBIRTHDATE"
        _previousbirthdate.Caption = "Previousbirthdate"
        Me.Fields.Add(_previousbirthdate)
        '
        '_previousname
        '
        _previousname.Name = "PREVIOUSNAME"
        _previousname.Caption = "Previousname"
        _previousname.MaxLength = 150
        _previousname.MultiLine = True
        Me.Fields.Add(_previousname)
        '
        '_children
        '
        _children.Name = "CHILDREN"
        _children.Caption = "Children"
        Me.Fields.Add(_children)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Lettertype
    ''' </summary>
    <System.ComponentModel.Description("Lettertype")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [LETTERTYPECODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _lettertypecodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Letterchildversion
    ''' </summary>
    <System.ComponentModel.Description("Letterchildversion")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [LETTERCHILDVERSIONCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _letterchildversioncodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Fulfillmentstatus
    ''' </summary>
    <System.ComponentModel.Description("Fulfillmentstatus")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [FULFILLMENTSTATUSCODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _fulfillmentstatuscodeid
        End Get
    End Property
    
    ''' <summary>
    ''' Resend
    ''' </summary>
    <System.ComponentModel.Description("Resend")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [RESENDCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of RESENDCODES))
        Get
            Return _resendcode
        End Get
    End Property
    
    ''' <summary>
    ''' Eftbrochure
    ''' </summary>
    <System.ComponentModel.Description("Eftbrochure")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [EFTBROCHURE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _eftbrochure
        End Get
    End Property
    
    ''' <summary>
    ''' Departedchild
    ''' </summary>
    <System.ComponentModel.Description("Departedchild")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [DEPARTEDCHILDID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _departedchildid
        End Get
    End Property
    
    ''' <summary>
    ''' Unavilablechild
    ''' </summary>
    <System.ComponentModel.Description("Unavilablechild")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [UNAVILABLECHILDID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _unavilablechildid
        End Get
    End Property
    
    ''' <summary>
    ''' Doublesponsoredchild
    ''' </summary>
    <System.ComponentModel.Description("Doublesponsoredchild")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [DOUBLESPONSOREDCHILDID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _doublesponsoredchildid
        End Get
    End Property
    
    ''' <summary>
    ''' Transferchild
    ''' </summary>
    <System.ComponentModel.Description("Transferchild")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [TRANSFERCHILDID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _transferchildid
        End Get
    End Property
    
    ''' <summary>
    ''' Previouschildproject
    ''' </summary>
    <System.ComponentModel.Description("Previouschildproject")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PREVIOUSCHILDPROJECTID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _previouschildprojectid
        End Get
    End Property
    
    ''' <summary>
    ''' Previousbirthdate
    ''' </summary>
    <System.ComponentModel.Description("Previousbirthdate")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PREVIOUSBIRTHDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _previousbirthdate
        End Get
    End Property
    
    ''' <summary>
    ''' Previousname
    ''' </summary>
    <System.ComponentModel.Description("Previousname")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [PREVIOUSNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _previousname
        End Get
    End Property
    
    ''' <summary>
    ''' Children
    ''' </summary>
    <System.ComponentModel.Description("Children")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CHILDREN]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of InteractionExtensionAddFormCHILDRENUIModel)
        Get
            Return _children
        End Get
    End Property
    
End Class
