Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Rate Change response scanner form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "918488ee-99d8-42b6-980e-458225d73172", "4bc1e218-eda2-4478-a899-d80ef4675ef6", "Letterscanner")> _
Partial Public Class [RateChangeResponseScannerFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _barcode As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _scanstatus As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _barcodeelements As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of RateChangeResponseScannerFormBARCODEELEMENTSUIModel)
    Private WithEvents _submit As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
	Private WithEvents _sponsorlookupid As Global.Blackbaud.AppFx.UIModeling.Core.StringField
	Private WithEvents _sponsorname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
	Private WithEvents _commitchangesbutton As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
	Private WithEvents _responseid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
	Private WithEvents _saveresponsebutton As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction


	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _barcode = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _scanstatus = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _barcodeelements = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of RateChangeResponseScannerFormBARCODEELEMENTSUIModel)
        _submit = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
		_sponsorlookupid = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
		_sponsorname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _commitchangesbutton = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
		_responseid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
		_saveresponsebutton = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction


        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New Guid("918488ee-99d8-42b6-980e-458225d73172")
        MyBase.DataFormInstanceId = New Guid("4bc1e218-eda2-4478-a899-d80ef4675ef6")
        MyBase.RecordType = "Letterscanner"
		MyBase.FORMHEADER.Value = "Rate Increase Response Scanner"
		MyBase.UserInterfaceUrl = "browser/htmlforms/custom/RateChangeResponseScannerForm.html"

        '
        '_barcode
        '
        _barcode.Name = "BARCODE"
        _barcode.Caption = "Bar code"
        _barcode.MaxLength = 20
        Me.Fields.Add(_barcode)
        '
        '_scanstatus
        '
        _scanstatus.Name = "SCANSTATUS"
        _scanstatus.Caption = "Scan status"
		_scanstatus.MaxLength = 1000
		'Turn this field off, not used:
		_scanstatus.Visible = False
        Me.Fields.Add(_scanstatus)
        '
        '_barcodeelements
        '
        _barcodeelements.Name = "BARCODEELEMENTS"
        _barcodeelements.Caption = "Scan Results"
        _barcodeelements.EnablePaging = True
		_barcodeelements.ItemsPerPage = 12
		_barcodeelements.AllowAdd = False
		_barcodeelements.AllowDelete = False
		Me.Fields.Add(_barcodeelements)
        '
        '_submit
        '
        _submit.Name = "SUBMIT"
        _submit.Caption = "Save results"
        Me.Fields.Add(_submit)
        '
        '_sponsorlookupid
        '
        _sponsorlookupid.Name = "SPONSORLOOKUPID"
		_sponsorlookupid.Caption = "Sponsor Lookup ID"
		Me.Fields.Add(_sponsorlookupid)
		'
		'_sponsorname
		'
		_sponsorname.Name = "SPONSORNAME"
		_sponsorname.Caption = "Sponsor Name"
		Me.Fields.Add(_sponsorname)
		'
        '_commitchangesbutton
        '
        _commitchangesbutton.Name = "COMMITCHANGESBUTTON"
        _commitchangesbutton.Caption = "Commit Changes"
        Me.Actions.Add(_commitchangesbutton)
		'
		'_responseid
		'
		_responseid.Name = "RESPONSEID"
		_responseid.Caption = "Response"
		_responseid.Required = True
		_responseid.SimpleDataListId = New Guid("e48745a4-b8cd-4e31-885a-3173d7374ea6")
		_responseid.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("RESPONSECATEGORYID", "CD350A82-B50C-44ED-B887-3FC5A326F96D"))
		Me.Fields.Add(_responseid)
		'
		'_saveresponsebutton
		'
		_saveresponsebutton.Name = "SAVERESPONSEBUTTON"
		_saveresponsebutton.Caption = "Save Response"
		Me.Actions.Add(_saveresponsebutton)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Bar code
    ''' </summary>
    <System.ComponentModel.Description("Bar code")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [BARCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _barcode
        End Get
    End Property
    
    ''' <summary>
    ''' Scan status
    ''' </summary>
    <System.ComponentModel.Description("Scan status")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SCANSTATUS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _scanstatus
        End Get
    End Property
    
    ''' <summary>
    ''' Scan Results
    ''' </summary>
    <System.ComponentModel.Description("Scan Results")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [BARCODEELEMENTS]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of RateChangeResponseScannerFormBARCODEELEMENTSUIModel)
        Get
            Return _barcodeelements
        End Get
    End Property
    
    ''' <summary>
    ''' Save results
    ''' </summary>
    <System.ComponentModel.Description("Save results")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SUBMIT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _submit
        End Get
    End Property
    
    ''' <summary>
    ''' Sponsor Lookup ID
    ''' </summary>
    <System.ComponentModel.Description("Sponsor Lookup ID")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SPONSORLOOKUPID]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _sponsorlookupid
        End Get
    End Property
	''' <summary>
	''' Sponsor Name
	''' </summary>
	<System.ComponentModel.Description("Sponsor Name")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [SPONSORNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
		Get
			Return _sponsorname
		End Get
	End Property

    ''' <summary>
    ''' Commit Changes
    ''' </summary>
    <System.ComponentModel.Description("Commit Changes")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [COMMITCHANGESBUTTON]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _commitchangesbutton
        End Get
    End Property

	''' <summary>
	''' Response
	''' </summary>
	<System.ComponentModel.Description("Response")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [RESPONSEID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
		Get
			Return _responseid
		End Get
	End Property

	''' <summary>
	''' Save Response
	''' </summary>
	<System.ComponentModel.Description("Save Response")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [SAVERESPONSEBUTTON]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
		Get
			Return _saveresponsebutton
		End Get
	End Property

End Class
