Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'RateChangeResponseScannerFormBARCODEELEMENTS' data form
''' </summary>
Partial Public Class [RateChangeResponseScannerFormBARCODEELEMENTSUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.UIModel

#Region "Extensibility methods"


    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _rateincrease As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _sponsorshipcommitmentid As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _childlookupid As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _childname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _currentrgamount As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
    Private WithEvents _rgfrequency As Global.Blackbaud.AppFx.UIModeling.Core.StringField
	Private WithEvents _newrgamount As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
	Private WithEvents _revenuelookupid As Global.Blackbaud.AppFx.UIModeling.Core.StringField
	Private WithEvents _sponsorlookupid As Global.Blackbaud.AppFx.UIModeling.Core.StringField
	Private WithEvents _sponsorshipid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
	Private WithEvents _sponsorid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
	Private WithEvents _segmentcategory As Global.Blackbaud.AppFx.UIModeling.Core.StringField
	Private WithEvents _constituentappealid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField


	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _rateincrease = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _sponsorshipcommitmentid = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _childlookupid = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _childname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _currentrgamount = New Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        _rgfrequency = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
		_newrgamount = New Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
		_revenuelookupid = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
		_sponsorlookupid = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
		_sponsorshipid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
		_sponsorid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
		_segmentcategory = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
		_constituentappealid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField


        '
        '_rateincrease
        '
        _rateincrease.Name = "RATEINCREASE"
        _rateincrease.Caption = "Increase ?"
        Me.Fields.Add(_rateincrease)

		'
		'_newrgamount
		'
		_newrgamount.Name = "NEWRGAMOUNT"
		_newrgamount.Caption = "New Amount"
		_newrgamount.Required = True
		Me.Fields.Add(_newrgamount)
		'
		'_currentrgamount
		'
		_currentrgamount.Name = "CURRENTRGAMOUNT"
		_currentrgamount.Caption = "Current Amount"
		_currentrgamount.DBReadOnly = True
		_currentrgamount.Enabled = False
		Me.Fields.Add(_currentrgamount)

		'
        '_sponsorshipcommitmentid
        '
        _sponsorshipcommitmentid.Name = "SPONSORSHIPCOMMITMENTID"
		_sponsorshipcommitmentid.Caption = "Commitment Id"
        _sponsorshipcommitmentid.DBReadOnly = True
		_sponsorshipcommitmentid.Enabled = False
        Me.Fields.Add(_sponsorshipcommitmentid)
        '
        '_childlookupid
        '
        _childlookupid.Name = "CHILDLOOKUPID"
		_childlookupid.Caption = "Child Id"
        _childlookupid.DBReadOnly = True
		_childlookupid.Enabled = False
        Me.Fields.Add(_childlookupid)
        '
        '_childname
        '
        _childname.Name = "CHILDNAME"
        _childname.Caption = "Child Name"
        _childname.DBReadOnly = True
		_childname.Enabled = False
        Me.Fields.Add(_childname)
		'
        '_rgfrequency
        '
        _rgfrequency.Name = "RGFREQUENCY"
        _rgfrequency.Caption = "Gift Frequency"
		_rgfrequency.DBReadOnly = True
		_rgfrequency.Enabled = False
        Me.Fields.Add(_rgfrequency)

		'
		'_revenuelookupid
		'
		_revenuelookupid.Name = "REVENUELOOKUPID"
		_revenuelookupid.Caption = "Revenue Id"
		_revenuelookupid.DBReadOnly = True
		_revenuelookupid.Enabled = False
		Me.Fields.Add(_revenuelookupid)

		'
		'_sponsorlookupid
		'
		_sponsorlookupid.Name = "SPONSORLOOKUPID"
		_sponsorlookupid.Caption = "Sponsor Id"
		_sponsorlookupid.DBReadOnly = True
		_sponsorlookupid.Enabled = False
		_sponsorlookupid.Visible = False
		Me.Fields.Add(_sponsorlookupid)

		'
		'_sponsorshipid
		'
		_sponsorshipid.Name = "SPONSORSHIPID"
		_sponsorshipid.Caption = "Sponsorship Id"
		_sponsorshipid.DBReadOnly = True
		_sponsorshipid.Visible = False
		_sponsorshipid.Enabled = False
		Me.Fields.Add(_sponsorshipid)

		'
		'_sponsorid
		'
		_sponsorid.Name = "SPONSORID"
		_sponsorid.Caption = "Sponsor Id"
		_sponsorid.DBReadOnly = True
		_sponsorid.Visible = False
		_sponsorid.Enabled = False
		Me.Fields.Add(_sponsorid)

		'
		'_segmentcategory
		'
		_segmentcategory.Name = "SEGMENTCATEGORY"
		_segmentcategory.Caption = "Segment Category"
		_segmentcategory.DBReadOnly = True
		_segmentcategory.Enabled = False
		_segmentcategory.Visible = False
		Me.Fields.Add(_segmentcategory)

		'
		'_constituentappealid
		'
		_constituentappealid.Name = "CONSTITUENTAPPEALID"
		_constituentappealid.Caption = "Constituent Appeal Id"
		_constituentappealid.DBReadOnly = True
		_constituentappealid.Visible = False
		_constituentappealid.Enabled = False
		Me.Fields.Add(_constituentappealid)


		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Increase ?
    ''' </summary>
    <System.ComponentModel.Description("Increase ?")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [RATEINCREASE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _rateincrease
        End Get
    End Property
    
    ''' <summary>
    ''' Sponsorship Commitment Lookup Id
    ''' </summary>
	<System.ComponentModel.Description("Commitment Id")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [SPONSORSHIPCOMMITMENTID]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
		Get
			Return _sponsorshipcommitmentid
		End Get
	End Property
    
    ''' <summary>
    ''' Child Lookup Id
    ''' </summary>
	<System.ComponentModel.Description("Child Id")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [CHILDLOOKUPID]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
		Get
			Return _childlookupid
		End Get
	End Property
    
    ''' <summary>
    ''' Child Name
    ''' </summary>
    <System.ComponentModel.Description("Child Name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CHILDNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _childname
        End Get
    End Property
    
    ''' <summary>
    ''' Current RG Amount
    ''' </summary>
	<System.ComponentModel.Description("Current Amount")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [CURRENTRGAMOUNT]() As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
		Get
			Return _currentrgamount
		End Get
	End Property
    
    ''' <summary>
    ''' Gift Frequency
    ''' </summary>
    <System.ComponentModel.Description("Gift Frequency")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [RGFREQUENCY]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _rgfrequency
        End Get
    End Property
    
    ''' <summary>
    ''' New RG Amount
    ''' </summary>
	<System.ComponentModel.Description("New Amount")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [NEWRGAMOUNT]() As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
		Get
			Return _newrgamount
		End Get
	End Property

	''' <summary>
	''' Revenue Lookup Id
	''' </summary>
	<System.ComponentModel.Description("Revenue Id")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [REVENUELOOKUPID]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
		Get
			Return _revenuelookupid
		End Get
	End Property

	''' <summary>
	''' Sponsor Lookup Id
	''' </summary>
	<System.ComponentModel.Description("Sponsor Id")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [SPONSORLOOKUPID]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
		Get
			Return _sponsorlookupid
		End Get
	End Property

	''' <summary>
	''' Sponsorship Id
	''' </summary>
	<System.ComponentModel.Description("Sponsorship Id")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [SPONSORSHIPID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
		Get
			Return _sponsorshipid
		End Get
	End Property

	''' <summary>
	''' Sponsor Id
	''' </summary>
	<System.ComponentModel.Description("Sponsor Id")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [SPONSORID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
		Get
			Return _sponsorid
		End Get
	End Property

	''' <summary>
	''' Constituent Appeal Id
	''' </summary>
	<System.ComponentModel.Description("Constituent Appeal Id")> _
 <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
 Public ReadOnly Property [CONSTITUENTAPPEALID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
		Get
			Return _constituentappealid
		End Get
	End Property

	''' <summary>
	''' Segment Category
	''' </summary>
	<System.ComponentModel.Description("Segment Category")> _
 <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
 Public ReadOnly Property [SEGMENTCATEGORY]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
		Get
			Return _segmentcategory
		End Get
	End Property

End Class
