Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Common UI Model Version' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "9eff16fe-43b4-42f7-864c-ddb5421ffb42", "555c9b42-9d55-498a-8f31-fdeccb9d0cfe", "Interaction Extension")> _
Partial Public Class [CommonUIModelVersionUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _version As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _version = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New Guid("9eff16fe-43b4-42f7-864c-ddb5421ffb42")
        MyBase.DataFormInstanceId = New Guid("555c9b42-9d55-498a-8f31-fdeccb9d0cfe")
        MyBase.RecordType = "Interaction Extension"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/Common.UIModelVersion.ViewForm.html"

        '
        '_version
        '
        _version.Name = "VERSION"
        _version.Caption = "Common UI Model:"
        _version.DBReadOnly = True
        _version.MaxLength = 50
        Me.Fields.Add(_version)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Common UI Model
    ''' </summary>
    <System.ComponentModel.Description("Common UI Model")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [VERSION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _version
        End Get
    End Property
    
End Class
