Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Child Pending Reasons Global Change' data form
''' </summary>

Partial Public Class [ChildPendingReasonsGlobalChangeUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.CustomUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the OPERATION property
    ''' </summary>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Enum OPERATIONS As Integer
        [Add] = 1
        [Replace] = 2
        [Delete] = 3
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _idsetregisterid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _recordtypeid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _operation As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of OPERATIONS))
    Private WithEvents _addpendingreasonvalue As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _reasontype As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
    Private WithEvents _overwriteexistingvalue As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _replacependingreasonvalue As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _replacependingreasonwithvalue As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _deletependingreasonvalue As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _deleteallvalues As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _idsetregisterid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _recordtypeid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _operation = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of OPERATIONS))
        _addpendingreasonvalue = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _reasontype = New Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
        _overwriteexistingvalue = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _replacependingreasonvalue = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _replacependingreasonwithvalue = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _deletependingreasonvalue = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _deleteallvalues = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

		MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ChildPendingReasonsGlobalChange.html"

        '
        '_idsetregisterid
        '
        _idsetregisterid.Name = "IDSETREGISTERID"
        _idsetregisterid.Caption = "Selection"
        _idsetregisterid.Required = True
        _idsetregisterid.SearchListID = New Guid("98d0070e-c4a7-495b-a438-2ac12da79068")
        _idsetregisterid.EnableQuickFind = True
        _idsetregisterid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "RECORDTYPEID", .Caption = "Record type", .ReadOnly = True, .DefaultValueText = "Fields!RECORDTYPEID"})
        _idsetregisterid.SystemSearchType = Global.Blackbaud.AppFx.UIModeling.Core.SystemSearchType.Selection
        Me.Fields.Add(_idsetregisterid)
        '
        '_recordtypeid
        '
        _recordtypeid.Name = "RECORDTYPEID"
        _recordtypeid.Caption = "RECORDTYPEID"
        _recordtypeid.Visible = False
        _recordtypeid.DBReadOnly = True
        Me.Fields.Add(_recordtypeid)
        '
        '_operation
        '
        _operation.Name = "OPERATION"
        _operation.Caption = "Operation"
        _operation.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of OPERATIONS)) With {.Value = OPERATIONS.[Add], .Translation = "Add"})
        _operation.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of OPERATIONS)) With {.Value = OPERATIONS.[Replace], .Translation = "Replace"})
        _operation.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of OPERATIONS)) With {.Value = OPERATIONS.[Delete], .Translation = "Delete"})
        Me.Fields.Add(_operation)
        '
        '_addpendingreasonvalue
        '
        _addpendingreasonvalue.Name = "ADDPENDINGREASONVALUE"
        _addpendingreasonvalue.Caption = "Pending reason"
		'_addpendingreasonvalue.Required = True
        _addpendingreasonvalue.SimpleDataListID = New Guid("c8d3128e-a2eb-4413-b0b4-1585ad5bf001")
        _addpendingreasonvalue.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("TYPE", "PARENT.Fields!REASONTYPE"))
        Me.Fields.Add(_addpendingreasonvalue)
        '
        '_reasontype
        '
        _reasontype.Name = "REASONTYPE"
        _reasontype.Caption = "REASONTYPE"
        _reasontype.Visible = False
        _reasontype.DBReadOnly = True
        Me.Fields.Add(_reasontype)
        '
        '_overwriteexistingvalue
        '
        _overwriteexistingvalue.Name = "OVERWRITEEXISTINGVALUE"
        _overwriteexistingvalue.Caption = "Overwrite existing value"
        Me.Fields.Add(_overwriteexistingvalue)
        '
        '_replacependingreasonvalue
        '
        _replacependingreasonvalue.Name = "REPLACEPENDINGREASONVALUE"
		_replacependingreasonvalue.Caption = "Replace pending reason value of"
		_replacependingreasonvalue.SimpleDataListId = New Guid("c8d3128e-a2eb-4413-b0b4-1585ad5bf001")
		_replacependingreasonvalue.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("TYPE", "PARENT.Fields!REASONTYPE"))
		Me.Fields.Add(_replacependingreasonvalue)
		'
		'_replacependingreasonwithvalue
		'
		_replacependingreasonwithvalue.Name = "REPLACEPENDINGREASONWITHVALUE"
		_replacependingreasonwithvalue.Caption = "Replace pending reason with"
		_replacependingreasonwithvalue.SimpleDataListId = New Guid("c8d3128e-a2eb-4413-b0b4-1585ad5bf001")
		_replacependingreasonwithvalue.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("TYPE", "PARENT.Fields!REASONTYPE"))
		Me.Fields.Add(_replacependingreasonwithvalue)
		'
		'_deletependingreasonvalue
		'
		_deletependingreasonvalue.Name = "DELETEPENDINGREASONVALUE"
		_deletependingreasonvalue.Caption = "Delete pending reason value"
		_deletependingreasonvalue.SimpleDataListId = New Guid("c8d3128e-a2eb-4413-b0b4-1585ad5bf001")
		_deletependingreasonvalue.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("TYPE", "PARENT.Fields!REASONTYPE"))
		Me.Fields.Add(_deletependingreasonvalue)
		'
		'_deleteallvalues
		'
		_deleteallvalues.Name = "DELETEALLVALUES"
		_deleteallvalues.Caption = "Delete all pending reason values"
		Me.Fields.Add(_deleteallvalues)

		OnCreated()

	End Sub

	''' <summary>
	''' Selection
	''' </summary>
	<System.ComponentModel.Description("Selection")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [IDSETREGISTERID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
		Get
			Return _idsetregisterid
		End Get
	End Property

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [RECORDTYPEID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
		Get
			Return _recordtypeid
		End Get
	End Property

	''' <summary>
	''' Operation
	''' </summary>
	<System.ComponentModel.Description("Operation")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [OPERATION]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of OPERATIONS))
		Get
			Return _operation
		End Get
	End Property

	''' <summary>
	''' Pending reason
	''' </summary>
	<System.ComponentModel.Description("Pending reason")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [ADDPENDINGREASONVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
		Get
			Return _addpendingreasonvalue
		End Get
	End Property

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [REASONTYPE]() As Global.Blackbaud.AppFx.UIModeling.Core.TinyIntField
		Get
			Return _reasontype
		End Get
	End Property

	''' <summary>
	''' Overwrite existing value
	''' </summary>
	<System.ComponentModel.Description("Overwrite existing value")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [OVERWRITEEXISTINGVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
		Get
			Return _overwriteexistingvalue
		End Get
	End Property

	''' <summary>
	''' Replace pending reason value of
	''' </summary>
	<System.ComponentModel.Description("Replace pending reason value of")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [REPLACEPENDINGREASONVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
		Get
			Return _replacependingreasonvalue
		End Get
	End Property

	''' <summary>
	''' Replace pending reason with
	''' </summary>
	<System.ComponentModel.Description("Replace pending reason with")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [REPLACEPENDINGREASONWITHVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
		Get
			Return _replacependingreasonwithvalue
		End Get
	End Property

	''' <summary>
	''' Delete pending reason value
	''' </summary>
	<System.ComponentModel.Description("Delete pending reason value")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [DELETEPENDINGREASONVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
		Get
			Return _deletependingreasonvalue
		End Get
	End Property

	''' <summary>
	''' Delete all pending reason values
	''' </summary>
	<System.ComponentModel.Description("Delete all pending reason values")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [DELETEALLVALUES]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
		Get
			Return _deleteallvalues
		End Get
	End Property
    
End Class
