Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Child Extension Departure Form Received Date Global Change' data form
''' </summary>

Partial Public Class [ChildExtensionDepartureFormReceivedDateGlobalChangeUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.CustomUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the OPERATION property
    ''' </summary>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Enum OPERATIONS As Integer
        [Add] = 1
        [Replace] = 2
        [Delete] = 3
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _idsetregisterid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _recordtypeid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _operation As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of OPERATIONS))
    Private WithEvents _adddepartureformreceiveddatevalue As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _overwriteexistingvalue As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _replacedepartureformreceiveddatevalue As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _replacedepartureformreceiveddatewithvalue As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _deletedepartureformreceiveddatevalue As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _deleteallvalues As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _idsetregisterid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _recordtypeid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _operation = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of OPERATIONS))
        _adddepartureformreceiveddatevalue = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _overwriteexistingvalue = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _replacedepartureformreceiveddatevalue = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _replacedepartureformreceiveddatewithvalue = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _deletedepartureformreceiveddatevalue = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _deleteallvalues = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

		MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ChildExtensionDepartureFormReceivedDateGlobalChange.html"

        '
        '_idsetregisterid
        '
        _idsetregisterid.Name = "IDSETREGISTERID"
        _idsetregisterid.Caption = "Selection"
        _idsetregisterid.Required = True
        _idsetregisterid.SearchListID = New Guid("98d0070e-c4a7-495b-a438-2ac12da79068")
        _idsetregisterid.EnableQuickFind = True
        _idsetregisterid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "RECORDTYPEID", .Caption = "Record type", .ReadOnly = True, .DefaultValueText = "Fields!RECORDTYPEID"})
        _idsetregisterid.SystemSearchType = Global.Blackbaud.AppFx.UIModeling.Core.SystemSearchType.Selection
        Me.Fields.Add(_idsetregisterid)
        '
        '_recordtypeid
        '
        _recordtypeid.Name = "RECORDTYPEID"
        _recordtypeid.Caption = "RECORDTYPEID"
        _recordtypeid.Visible = False
        _recordtypeid.DBReadOnly = True
        Me.Fields.Add(_recordtypeid)
        '
        '_operation
        '
        _operation.Name = "OPERATION"
        _operation.Caption = "Operation"
        _operation.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of OPERATIONS)) With {.Value = OPERATIONS.[Add], .Translation = "Add"})
        _operation.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of OPERATIONS)) With {.Value = OPERATIONS.[Replace], .Translation = "Replace"})
        _operation.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of OPERATIONS)) With {.Value = OPERATIONS.[Delete], .Translation = "Delete"})
        Me.Fields.Add(_operation)
        '
        '_adddepartureformreceiveddatevalue
        '
        _adddepartureformreceiveddatevalue.Name = "ADDDEPARTUREFORMRECEIVEDDATEVALUE"
        _adddepartureformreceiveddatevalue.Caption = "Departure form received date"
        Me.Fields.Add(_adddepartureformreceiveddatevalue)
        '
        '_overwriteexistingvalue
        '
        _overwriteexistingvalue.Name = "OVERWRITEEXISTINGVALUE"
        _overwriteexistingvalue.Caption = "Overwrite existing value"
        Me.Fields.Add(_overwriteexistingvalue)
        '
        '_replacedepartureformreceiveddatevalue
        '
        _replacedepartureformreceiveddatevalue.Name = "REPLACEDEPARTUREFORMRECEIVEDDATEVALUE"
        _replacedepartureformreceiveddatevalue.Caption = "Replace departure form received date value of"
        Me.Fields.Add(_replacedepartureformreceiveddatevalue)
        '
        '_replacedepartureformreceiveddatewithvalue
        '
        _replacedepartureformreceiveddatewithvalue.Name = "REPLACEDEPARTUREFORMRECEIVEDDATEWITHVALUE"
        _replacedepartureformreceiveddatewithvalue.Caption = "Replace departure form received date with"
        Me.Fields.Add(_replacedepartureformreceiveddatewithvalue)
        '
        '_deletedepartureformreceiveddatevalue
        '
        _deletedepartureformreceiveddatevalue.Name = "DELETEDEPARTUREFORMRECEIVEDDATEVALUE"
        _deletedepartureformreceiveddatevalue.Caption = "Delete departure form received date value"
        Me.Fields.Add(_deletedepartureformreceiveddatevalue)
        '
        '_deleteallvalues
        '
        _deleteallvalues.Name = "DELETEALLVALUES"
        _deleteallvalues.Caption = "Delete all departure form received departure form received date values"
        Me.Fields.Add(_deleteallvalues)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Selection
    ''' </summary>
    <System.ComponentModel.Description("Selection")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [IDSETREGISTERID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _idsetregisterid
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [RECORDTYPEID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _recordtypeid
        End Get
    End Property
    
    ''' <summary>
    ''' Operation
    ''' </summary>
    <System.ComponentModel.Description("Operation")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [OPERATION]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of OPERATIONS))
        Get
            Return _operation
        End Get
    End Property
    
    ''' <summary>
    ''' Departure form received date
    ''' </summary>
    <System.ComponentModel.Description("Departure form received date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [ADDDEPARTUREFORMRECEIVEDDATEVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _adddepartureformreceiveddatevalue
        End Get
    End Property
    
    ''' <summary>
    ''' Overwrite existing value
    ''' </summary>
    <System.ComponentModel.Description("Overwrite existing value")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [OVERWRITEEXISTINGVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _overwriteexistingvalue
        End Get
    End Property
    
    ''' <summary>
    ''' Replace departure form received date value of
    ''' </summary>
    <System.ComponentModel.Description("Replace departure form received date value of")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [REPLACEDEPARTUREFORMRECEIVEDDATEVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _replacedepartureformreceiveddatevalue
        End Get
    End Property
    
    ''' <summary>
    ''' Replace departure form received date with
    ''' </summary>
    <System.ComponentModel.Description("Replace departure form received date with")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [REPLACEDEPARTUREFORMRECEIVEDDATEWITHVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _replacedepartureformreceiveddatewithvalue
        End Get
    End Property
    
    ''' <summary>
    ''' Delete departure form received date value
    ''' </summary>
    <System.ComponentModel.Description("Delete departure form received date value")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [DELETEDEPARTUREFORMRECEIVEDDATEVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _deletedepartureformreceiveddatevalue
        End Get
    End Property
    
    ''' <summary>
    ''' Delete all departure form received departure form received date values
    ''' </summary>
    <System.ComponentModel.Description("Delete all departure form received departure form received date values")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [DELETEALLVALUES]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _deleteallvalues
        End Get
    End Property
    
End Class
