Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Child Extension Fulfillment Status Global Change' data form
''' </summary>

Partial Public Class [ChildExtensionFulfillmentStatusGlobalChangeUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.CustomUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the OPERATION property
    ''' </summary>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Enum OPERATIONS As Integer
        [Add] = 1
        [Replace] = 2
        [Delete] = 3
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _idsetregisterid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _recordtypeid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _operation As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of OPERATIONS))
    Private WithEvents _addfulfillmentstatusvalue As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _overwriteexistingvalue As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _replacefulfillmentstatusvalue As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _replacefulfillmentstatuswithvalue As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _deletefulfillmentstatusvalue As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _deleteallvalues As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _idsetregisterid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _recordtypeid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _operation = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of OPERATIONS))
        _addfulfillmentstatusvalue = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _overwriteexistingvalue = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _replacefulfillmentstatusvalue = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _replacefulfillmentstatuswithvalue = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _deletefulfillmentstatusvalue = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _deleteallvalues = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ChildExtensionFulfillmentStatusGlobalChange.html"

        '
        '_idsetregisterid
        '
        _idsetregisterid.Name = "IDSETREGISTERID"
        _idsetregisterid.Caption = "Selection"
        _idsetregisterid.Required = True
        _idsetregisterid.SearchListID = New Guid("98d0070e-c4a7-495b-a438-2ac12da79068")
        _idsetregisterid.EnableQuickFind = True
        _idsetregisterid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "RECORDTYPEID", .Caption = "Record type", .ReadOnly = True, .DefaultValueText = "Fields!RECORDTYPEID"})
        _idsetregisterid.SystemSearchType = Global.Blackbaud.AppFx.UIModeling.Core.SystemSearchType.Selection
        Me.Fields.Add(_idsetregisterid)
        '
        '_recordtypeid
        '
        _recordtypeid.Name = "RECORDTYPEID"
        _recordtypeid.Caption = "RECORDTYPEID"
        _recordtypeid.Visible = False
        _recordtypeid.DBReadOnly = True
        Me.Fields.Add(_recordtypeid)
        '
        '_operation
        '
        _operation.Name = "OPERATION"
        _operation.Caption = "Operation"
        _operation.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of OPERATIONS)) With {.Value = OPERATIONS.[Add], .Translation = "Add"})
        _operation.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of OPERATIONS)) With {.Value = OPERATIONS.[Replace], .Translation = "Replace"})
        _operation.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of OPERATIONS)) With {.Value = OPERATIONS.[Delete], .Translation = "Delete"})
        Me.Fields.Add(_operation)
        '
        '_addfulfillmentstatusvalue
        '
        _addfulfillmentstatusvalue.Name = "ADDFULFILLMENTSTATUSVALUE"
        _addfulfillmentstatusvalue.Caption = "Fulfillment status"
        _addfulfillmentstatusvalue.CodeTableName = "USR_FULFILLMENTSTATUSCODE"
        Me.Fields.Add(_addfulfillmentstatusvalue)
        '
        '_overwriteexistingvalue
        '
        _overwriteexistingvalue.Name = "OVERWRITEEXISTINGVALUE"
        _overwriteexistingvalue.Caption = "Overwrite existing value"
        Me.Fields.Add(_overwriteexistingvalue)
        '
        '_replacefulfillmentstatusvalue
        '
        _replacefulfillmentstatusvalue.Name = "REPLACEFULFILLMENTSTATUSVALUE"
        _replacefulfillmentstatusvalue.Caption = "Replace fulfillment status value of"
        _replacefulfillmentstatusvalue.CodeTableName = "USR_FULFILLMENTSTATUSCODE"
        Me.Fields.Add(_replacefulfillmentstatusvalue)
        '
        '_replacefulfillmentstatuswithvalue
        '
        _replacefulfillmentstatuswithvalue.Name = "REPLACEFULFILLMENTSTATUSWITHVALUE"
        _replacefulfillmentstatuswithvalue.Caption = "Replace fulfillment status with"
        _replacefulfillmentstatuswithvalue.CodeTableName = "USR_FULFILLMENTSTATUSCODE"
        Me.Fields.Add(_replacefulfillmentstatuswithvalue)
        '
        '_deletefulfillmentstatusvalue
        '
        _deletefulfillmentstatusvalue.Name = "DELETEFULFILLMENTSTATUSVALUE"
        _deletefulfillmentstatusvalue.Caption = "Delete fulfillment status value"
        _deletefulfillmentstatusvalue.CodeTableName = "USR_FULFILLMENTSTATUSCODE"
        Me.Fields.Add(_deletefulfillmentstatusvalue)
        '
        '_deleteallvalues
        '
        _deleteallvalues.Name = "DELETEALLVALUES"
        _deleteallvalues.Caption = "Delete all fulfillment status values"
        Me.Fields.Add(_deleteallvalues)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Selection
    ''' </summary>
    <System.ComponentModel.Description("Selection")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [IDSETREGISTERID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _idsetregisterid
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [RECORDTYPEID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _recordtypeid
        End Get
    End Property
    
    ''' <summary>
    ''' Operation
    ''' </summary>
    <System.ComponentModel.Description("Operation")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [OPERATION]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of OPERATIONS))
        Get
            Return _operation
        End Get
    End Property
    
    ''' <summary>
    ''' Fulfillment status
    ''' </summary>
    <System.ComponentModel.Description("Fulfillment status")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [ADDFULFILLMENTSTATUSVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _addfulfillmentstatusvalue
        End Get
    End Property
    
    ''' <summary>
    ''' Overwrite existing value
    ''' </summary>
    <System.ComponentModel.Description("Overwrite existing value")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [OVERWRITEEXISTINGVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _overwriteexistingvalue
        End Get
    End Property
    
    ''' <summary>
    ''' Replace fulfillment status value of
    ''' </summary>
    <System.ComponentModel.Description("Replace fulfillment status value of")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [REPLACEFULFILLMENTSTATUSVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _replacefulfillmentstatusvalue
        End Get
    End Property
    
    ''' <summary>
    ''' Replace fulfillment status with
    ''' </summary>
    <System.ComponentModel.Description("Replace fulfillment status with")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [REPLACEFULFILLMENTSTATUSWITHVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _replacefulfillmentstatuswithvalue
        End Get
    End Property
    
    ''' <summary>
    ''' Delete fulfillment status value
    ''' </summary>
    <System.ComponentModel.Description("Delete fulfillment status value")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [DELETEFULFILLMENTSTATUSVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _deletefulfillmentstatusvalue
        End Get
    End Property
    
    ''' <summary>
    ''' Delete all fulfillment status values
    ''' </summary>
    <System.ComponentModel.Description("Delete all fulfillment status values")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [DELETEALLVALUES]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _deleteallvalues
        End Get
    End Property
    
End Class
