Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Child Field Memo Start Date Global Change' data form
''' </summary>

Partial Public Class [ChildFieldMemoDateSentGlobalChangeUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.CustomUIModel

#Region "Extensibility methods"

	Partial Private Sub OnCreated()
	End Sub

#End Region

	Private WithEvents _idsetregisterid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
	Private WithEvents _recordtypeid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
	Private WithEvents _operation As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of String)
	Private WithEvents _adddatesentvalue As Global.Blackbaud.AppFx.UIModeling.Core.DateField
	Private WithEvents _overwriteexistingvalue As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
	Private WithEvents _replacedatesentvalue As Global.Blackbaud.AppFx.UIModeling.Core.DateField
	Private WithEvents _replacedatesentwithvalue As Global.Blackbaud.AppFx.UIModeling.Core.DateField
	Private WithEvents _deletedatesentvalue As Global.Blackbaud.AppFx.UIModeling.Core.DateField
	Private WithEvents _deletealldatesentvalues As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public Sub New()
		MyBase.New()

		_idsetregisterid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
		_recordtypeid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
		_operation = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of String)
		_adddatesentvalue = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
		_overwriteexistingvalue = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
		_replacedatesentvalue = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
		_replacedatesentwithvalue = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
		_deletedatesentvalue = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
		_deletealldatesentvalues = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

		MyBase.UserInterfaceUrl = "browser/htmlforms/custom/ChildFieldMemoStartDateGlobalChange.html"

		'
		'_idsetregisterid
		'
		_idsetregisterid.Name = "IDSETREGISTERID"
		_idsetregisterid.Caption = "Selection"
		_idsetregisterid.Required = True
		_idsetregisterid.SearchListID = New Guid("98d0070e-c4a7-495b-a438-2ac12da79068")
		_idsetregisterid.EnableQuickFind = True
		_idsetregisterid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "RECORDTYPEID", .Caption = "Record type", .ReadOnly = True, .DefaultValueText = "Fields!RECORDTYPEID"})
		_idsetregisterid.SystemSearchType = Global.Blackbaud.AppFx.UIModeling.Core.SystemSearchType.Selection
		Me.Fields.Add(_idsetregisterid)
		'
		'_recordtypeid
		'
		_recordtypeid.Name = "RECORDTYPEID"
		_recordtypeid.Caption = "RECORDTYPEID"
		_recordtypeid.Visible = False
		_recordtypeid.DBReadOnly = True
		Me.Fields.Add(_recordtypeid)
		'
		'_operation
		'
		_operation.Name = "OPERATION"
		_operation.Caption = "Operation"
		_operation.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of String) With {.Value = "1", .Translation = "Add"})
		_operation.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of String) With {.Value = "2", .Translation = "Replace"})
		_operation.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of String) With {.Value = "3", .Translation = "Delete"})
		Me.Fields.Add(_operation)
		'
		'_adddatesentvalue
		'
		_adddatesentvalue.Name = "ADDDATESENTVALUE"
		_adddatesentvalue.Caption = "Date sent"
		Me.Fields.Add(_adddatesentvalue)
		'
		'_overwriteexistingvalue
		'
		_overwriteexistingvalue.Name = "OVERWRITEEXISTINGVALUE"
		_overwriteexistingvalue.Caption = "Overwrite existing value"
		Me.Fields.Add(_overwriteexistingvalue)
		'
		'_replacedatesentvalue
		'
		_replacedatesentvalue.Name = "REPLACEDATESENTVALUE"
		_replacedatesentvalue.Caption = "Replace date sent value of"
		Me.Fields.Add(_replacedatesentvalue)
		'
		'_replacedatesentwithvalue
		'
		_replacedatesentwithvalue.Name = "REPLACEDATESENTWITHVALUE"
		_replacedatesentwithvalue.Caption = "Replace date sent with"
		Me.Fields.Add(_replacedatesentwithvalue)
		'
		'_deletedatesentvalue
		'
		_deletedatesentvalue.Name = "DELETEDATESENTVALUE"
		_deletedatesentvalue.Caption = "Delete date sent value"
		Me.Fields.Add(_deletedatesentvalue)
		'
		'_deletealldatesentvalues
		'
		_deletealldatesentvalues.Name = "DELETEALLDATESENTVALUES"
		_deletealldatesentvalues.Caption = "Delete all date sent values"
		Me.Fields.Add(_deletealldatesentvalues)

		OnCreated()

	End Sub

	''' <summary>
	''' Selection
	''' </summary>
	<System.ComponentModel.Description("Selection")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [IDSETREGISTERID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
		Get
			Return _idsetregisterid
		End Get
	End Property

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [RECORDTYPEID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
		Get
			Return _recordtypeid
		End Get
	End Property

	''' <summary>
	''' Operation
	''' </summary>
	<System.ComponentModel.Description("Operation")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [OPERATION]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of String)
		Get
			Return _operation
		End Get
	End Property

	''' <summary>
	''' Date sent
	''' </summary>
	<System.ComponentModel.Description("Date sent")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [ADDDATESENTVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
		Get
			Return _adddatesentvalue
		End Get
	End Property

	''' <summary>
	''' Overwrite existing value
	''' </summary>
	<System.ComponentModel.Description("Overwrite existing value")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [OVERWRITEEXISTINGVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
		Get
			Return _overwriteexistingvalue
		End Get
	End Property

	''' <summary>
	''' Replace date sent value of
	''' </summary>
	<System.ComponentModel.Description("Replace date sent value of")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [REPLACEDATESENTVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
		Get
			Return _replacedatesentvalue
		End Get
	End Property

	''' <summary>
	''' Replace date sent with
	''' </summary>
	<System.ComponentModel.Description("Replace date sent with")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [REPLACEDATESENTWITHVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
		Get
			Return _replacedatesentwithvalue
		End Get
	End Property

	''' <summary>
	''' Delete date sent value
	''' </summary>
	<System.ComponentModel.Description("Delete date sent value")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [DELETEDATESENTVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
		Get
			Return _deletedatesentvalue
		End Get
	End Property

	''' <summary>
	''' Delete all date sent values
	''' </summary>
	<System.ComponentModel.Description("Delete all date sent values")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [DELETEALLDATESENTVALUES]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
		Get
			Return _deletealldatesentvalues
		End Get
	End Property

End Class
