Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Fulfillment Status Interaction Global Change' data form
''' </summary>

Partial Public Class [FulfillmentStatusInteractionGlobalChangeUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.CustomUIModel


#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _idsetregisterid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _recordtypeid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
	Private WithEvents _operation As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of String)
	Private WithEvents _addvalue As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
	Private WithEvents _overwriteexistingvalue As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
	Private WithEvents _replacevalue As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
	Private WithEvents _replacewithvalue As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public Sub New()
		MyBase.New()

		_idsetregisterid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
		_recordtypeid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
		_operation = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of String)
		_addvalue = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
		_overwriteexistingvalue = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
		_replacevalue = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
		_replacewithvalue = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField

		MyBase.UserInterfaceUrl = "browser/htmlforms/custom/FulfillmentStatusInteractionGlobalChange.html"

		'
		'_idsetregisterid
		'
		_idsetregisterid.Name = "IDSETREGISTERID"
		_idsetregisterid.Caption = "Selection"
		_idsetregisterid.Required = True
		_idsetregisterid.SearchListID = New Guid("98d0070e-c4a7-495b-a438-2ac12da79068")
		_idsetregisterid.EnableQuickFind = True
		_idsetregisterid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "RECORDTYPEID", .Caption = "Record type", .ReadOnly = True, .DefaultValueText = "Fields!RECORDTYPEID"})
		_idsetregisterid.SystemSearchType = Global.Blackbaud.AppFx.UIModeling.Core.SystemSearchType.Selection
		Me.Fields.Add(_idsetregisterid)
		'
		'_recordtypeid
		'
		_recordtypeid.Name = "RECORDTYPEID"
		_recordtypeid.Caption = "RECORDTYPEID"
		_recordtypeid.Visible = False
		_recordtypeid.DBReadOnly = True
		Me.Fields.Add(_recordtypeid)
		'
		'_operation
		'
		_operation.Name = "OPERATION"
		_operation.Caption = "Operation"
		_operation.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of String) With {.Value = "1", .Translation = "Add"})
		_operation.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of String) With {.Value = "2", .Translation = "Replace"})
		Me.Fields.Add(_operation)
		'
		'_addvalue
		'
		_addvalue.Name = "ADDVALUE"
		_addvalue.Caption = "Fulfillment Status"
		_addvalue.CodeTableName = "USR_INTERACTIONEXTENSIONFULFILLMENTSTATUSCODE"
		Me.Fields.Add(_addvalue)
		'
		'_overwriteexistingvalue
		'
		_overwriteexistingvalue.Name = "OVERWRITEEXISTINGVALUE"
		_overwriteexistingvalue.Caption = "Overwrite existing value"
		Me.Fields.Add(_overwriteexistingvalue)
		'
		'_replacevalue
		'
		_replacevalue.Name = "REPLACEVALUE"
		_replacevalue.Caption = "Replace fulfillment status value of"
		_replacevalue.CodeTableName = "USR_INTERACTIONEXTENSIONFULFILLMENTSTATUSCODE"
		Me.Fields.Add(_replacevalue)
		'
		'_replacewithvalue
		'
		_replacewithvalue.Name = "REPLACEWITHVALUE"
		_replacewithvalue.Caption = "Replace fulfillment status with"
		_replacewithvalue.CodeTableName = "USR_INTERACTIONEXTENSIONFULFILLMENTSTATUSCODE"
		Me.Fields.Add(_replacewithvalue)

		OnCreated()

	End Sub

	''' <summary>
	''' Selection
	''' </summary>
	<System.ComponentModel.Description("Selection")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [IDSETREGISTERID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
		Get
			Return _idsetregisterid
		End Get
	End Property

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [RECORDTYPEID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
		Get
			Return _recordtypeid
		End Get
	End Property

	''' <summary>
	''' Operation
	''' </summary>
	<System.ComponentModel.Description("Operation")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [OPERATION]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of String)
		Get
			Return _operation
		End Get
	End Property
    
    ''' <summary>
    ''' Fulfillment Status
    ''' </summary>
	<System.ComponentModel.Description("Fulfillment Status")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [ADDVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
		Get
			Return _addvalue
		End Get
	End Property
    
    ''' <summary>
    ''' Overwrite existing value
    ''' </summary>
    <System.ComponentModel.Description("Overwrite existing value")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [OVERWRITEEXISTINGVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _overwriteexistingvalue
        End Get
    End Property
    
    ''' <summary>
    ''' Replace fulfillment status value of
    ''' </summary>
	<System.ComponentModel.Description("Replace fulfillment status value of")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [REPLACEVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
		Get
			Return _replacevalue
		End Get
	End Property
    
    ''' <summary>
    ''' Replace fulfillment status with
    ''' </summary>
	<System.ComponentModel.Description("Replace fulfillment status with")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [REPLACEWITHVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
		Get
			Return _replacewithvalue
		End Get
	End Property
    
End Class
