''' <summary>
''' Class that holds the Constant values for the Customized CodeTables in CRM.
''' 
''' </summary>
''' <history>
''' Date            Modified By     Comments
''' 4/23/12           Memphis        Initial version compiled between Cary's and Memphis' local instance
''' </history>
''' <remarks>These are generated from a SQL Query that is run manually and results are copied-and-pasted into this class</remarks>
Public Class CodeTableFields

    ' Months
    Public Const MONTH_APRIL As String = "MONTH_APRIL"
    Public Const MONTH_AUGUST As String = "MONTH_AUGUST"
    Public Const MONTH_DECEMBER As String = "MONTH_DECEMBER"
    Public Const MONTH_FEBRUARY As String = "MONTH_FEBRUARY"
    Public Const MONTH_JANUARY As String = "MONTH_JANUARY"
    Public Const MONTH_JULY As String = "MONTH_JULY"
    Public Const MONTH_JUNE As String = "MONTH_JUNE"
    Public Const MONTH_MARCH As String = "MONTH_MARCH"
    Public Const MONTH_MAY As String = "MONTH_MAY"
    Public Const MONTH_NOVEMBER As String = "MONTH_NOVEMBER"
    Public Const MONTH_OCTOBER As String = "MONTH_OCTOBER"
    Public Const MONTH_SEPTEMBER As String = "MONTH_SEPTEMBER"

    ' Child Project
    Public Const CHILDPROJECTMAXGRADELEVEL_APPRENTICESHIP As String = "CHILDPROJECTMAXGRADELEVEL_APPRENTICESHIP"
    Public Const CHILDPROJECTMAXGRADELEVEL_KINDERGARTEN As String = "CHILDPROJECTMAXGRADELEVEL_KINDERGARTEN"
    Public Const CHILDPROJECTMAXGRADELEVEL_OTHER As String = "CHILDPROJECTMAXGRADELEVEL_OTHER"
    Public Const CHILDPROJECTMAXGRADELEVEL_PRESCHOOL As String = "CHILDPROJECTMAXGRADELEVEL_PRESCHOOL"
    Public Const CHILDPROJECTMAXGRADELEVEL_PRIMARYSCHOOL As String = "CHILDPROJECTMAXGRADELEVEL_PRIMARYSCHOOL"
    Public Const CHILDPROJECTMAXGRADELEVEL_SECONDARYSCHOOL As String = "CHILDPROJECTMAXGRADELEVEL_SECONDARYSCHOOL"
    Public Const CHILDPROJECTMAXGRADELEVEL_VOCATIONALSCHOOL As String = "CHILDPROJECTMAXGRADELEVEL_VOCATIONALSCHOOL"

    ' Child Project Type
    Public Const CHILDPROJECTTYPE_CHILDDEVELOPMENTCENTER As String = "CHILDPROJECTTYPE_CHILDDEVELOPMENTCENTER"
    Public Const CHILDPROJECTTYPE_CHILDRENSHOMEPARENTSLIVING As String = "CHILDPROJECTTYPE_CHILDRENSHOMEPARENTSLIVING"
    Public Const CHILDPROJECTTYPE_MERCYCENTER As String = "CHILDPROJECTTYPE_MERCYCENTER"
    Public Const CHILDPROJECTTYPE_OPRHANGE As String = "CHILDPROJECTTYPE_OPRHANGE"
    Public Const CHILDPROJECTTYPE_OTHER As String = "CHILDPROJECTTYPE_OTHER"
    Public Const CHILDPROJECTTYPE_SCHOOL As String = "CHILDPROJECTTYPE_SCHOOL"

    ' Child Project Community Type
    Public Const CHILDPROJECTCOMMUNITYTYPE_RURAL As String = "CHILDPROJECTCOMMUNITYTYPE_RURAL"
    Public Const CHILDPROJECTCOMMUNITYTYPE_SUBURBAN As String = "CHILDPROJECTCOMMUNITYTYPE_SUBURBAN"
    Public Const CHILDPROJECTCOMMUNITYTYPE_URBAN As String = "CHILDPROJECTCOMMUNITYTYPE_URBAN"

    ' Child Project Terrain
    Public Const CHILDPROJECTTERRAIN_COASTAL As String = "CHILDPROJECTTERRAIN_COASTAL"
    Public Const CHILDPROJECTTERRAIN_DESERT As String = "CHILDPROJECTTERRAIN_DESERT"
    Public Const CHILDPROJECTTERRAIN_FOREST As String = "CHILDPROJECTTERRAIN_FOREST"
    Public Const CHILDPROJECTTERRAIN_HILLS As String = "CHILDPROJECTTERRAIN_HILLS"
    Public Const CHILDPROJECTTERRAIN_ISLAND As String = "CHILDPROJECTTERRAIN_ISLAND"
    Public Const CHILDPROJECTTERRAIN_JUNGLE As String = "CHILDPROJECTTERRAIN_JUNGLE"
    Public Const CHILDPROJECTTERRAIN_MOUNTANOUS As String = "CHILDPROJECTTERRAIN_MOUNTANOUS"
    Public Const CHILDPROJECTTERRAIN_OTHER As String = "CHILDPROJECTTERRAIN_OTHER"
    Public Const CHILDPROJECTTERRAIN_PLAINSORFLATLAND As String = "CHILDPROJECTTERRAIN_PLAINSORFLATLAND"

    ' Child Project Climate
    Public Const CHILDPROJECTCLIMATE_DRY As String = "CHILDPROJECTCLIMATE_DRY"
    Public Const CHILDPROJECTCLIMATE_HUMID As String = "CHILDPROJECTCLIMATE_HUMID"

    ' Religion
    Public Const RELIGION_ANIMIST As String = "RELIGION_ANIMIST"
    Public Const RELIGION_BUDDHIST As String = "RELIGION_BUDDHIST"
    Public Const RELIGION_CATHOLIC As String = "RELIGION_CATHOLIC"
    Public Const RELIGION_COPTIC As String = "RELIGION_COPTIC"
    Public Const RELIGION_HINDU As String = "RELIGION_HINDU"
    Public Const RELIGION_MUSLIM As String = "RELIGION_MUSLIM"
    Public Const RELIGION_ORTHODOX As String = "RELIGION_ORTHODOX"
    Public Const RELIGION_OTHER As String = "RELIGION_OTHER"
    Public Const RELIGION_PROTESTANT As String = "RELIGION_PROTESTANT"
    Public Const RELIGION_VOODOO As String = "RELIGION_VOODOO"
    Public Const RELIGION_WITCHCRAFT As String = "RELIGION_WITCHCRAFT"

    ' Child Project Highest Education
    Public Const CHILDPROJECTHIGHESTEDUCATION_NONE As String = "CHILDPROJECTHIGHESTEDUCATION_NONE"
    Public Const CHILDPROJECTHIGHESTEDUCATION_OTHER As String = "CHILDPROJECTHIGHESTEDUCATION_OTHER"
    Public Const CHILDPROJECTHIGHESTEDUCATION_PRIMARYSCHOOL As String = "CHILDPROJECTHIGHESTEDUCATION_PRIMARYSCHOOL"
    Public Const CHILDPROJECTHIGHESTEDUCATION_SECONDARYSCHOOL As String = "CHILDPROJECTHIGHESTEDUCATION_SECONDARYSCHOOL"
    Public Const CHILDPROJECTHIGHESTEDUCATION_UNIVERSITY As String = "CHILDPROJECTHIGHESTEDUCATION_UNIVERSITY"
    Public Const CHILDPROJECTHIGHESTEDUCATION_VOCATIONALTRAINING As String = "CHILDPROJECTHIGHESTEDUCATION_VOCATIONALTRAINING"

    ' Child Project Status
    Public Const CHILDPROJECTSTATUS_ACTIVE As String = "CHILDPROJECTSTATUS_ACTIVE"
    Public Const CHILDPROJECTSTATUS_ACTIVERESERVED As String = "CHILDPROJECTSTATUS_ACTIVERESERVED"
    Public Const CHILDPROJECTSTATUS_CLOSED As String = "CHILDPROJECTSTATUS_CLOSED"
    Public Const CHILDPROJECTSTATUS_PENDING As String = "CHILDPROJECTSTATUS_PENDING"
    Public Const CHILDPROJECTSTATUS_PHASINGOUT As String = "CHILDPROJECTSTATUS_PHASINGOUT"

    ' Child Project Performance
    Public Const CHILDPROJECTPERFORMANCE_GOOD As String = "CHILDPROJECTPERFORMANCE_GOOD"
    Public Const CHILDPROJECTPERFORMANCE_POOR As String = "CHILDPROJECTPERFORMANCE_POOR"

    ' Child Project Category
    Public Const CHILDPROJECTCATEGORY_FORGOTTENCHILDRENPROJECT As String = "CHILDPROJECTCATEGORY_FORGOTTENCHILDRENPROJECT"
    Public Const CHILDPROJECTCATEGORY_POVERTYPROJECT As String = "CHILDPROJECTCATEGORY_POVERTYPROJECT"

    ' Child Project Documentation Status
    Public Const CHILDPROJECTDOCUMENTATIONSTATUS_NO2008 As String = "CHILDPROJECTDOCUMENTATIONSTATUS_NO2008"
    Public Const CHILDPROJECTDOCUMENTATIONSTATUS_NO2009 As String = "CHILDPROJECTDOCUMENTATIONSTATUS_NO2009"
    Public Const CHILDPROJECTDOCUMENTATIONSTATUS_NO2010 As String = "CHILDPROJECTDOCUMENTATIONSTATUS_NO2010"
    Public Const CHILDPROJECTDOCUMENTATIONSTATUS_NO2011 As String = "CHILDPROJECTDOCUMENTATIONSTATUS_NO2011"
    Public Const CHILDPROJECTDOCUMENTATIONSTATUS_NO2012 As String = "CHILDPROJECTDOCUMENTATIONSTATUS_NO2012"
    Public Const CHILDPROJECTDOCUMENTATIONSTATUS_YES2008 As String = "CHILDPROJECTDOCUMENTATIONSTATUS_YES2008"
    Public Const CHILDPROJECTDOCUMENTATIONSTATUS_YES2009 As String = "CHILDPROJECTDOCUMENTATIONSTATUS_YES2009"
    Public Const CHILDPROJECTDOCUMENTATIONSTATUS_YES2010 As String = "CHILDPROJECTDOCUMENTATIONSTATUS_YES2010"
    Public Const CHILDPROJECTDOCUMENTATIONSTATUS_YES2011 As String = "CHILDPROJECTDOCUMENTATIONSTATUS_YES2011"
    Public Const CHILDPROJECTDOCUMENTATIONSTATUS_YES2012 As String = "CHILDPROJECTDOCUMENTATIONSTATUS_YES2012"

    ' Child Project Form Status
    Public Const CHILDPROJECTFORMSTATUS_2008YES As String = "CHILDPROJECTFORMSTATUS_2008YES"
    Public Const CHILDPROJECTFORMSTATUS_2009YES As String = "CHILDPROJECTFORMSTATUS_2009YES"
    Public Const CHILDPROJECTFORMSTATUS_2010YES As String = "CHILDPROJECTFORMSTATUS_2010YES"
    Public Const CHILDPROJECTFORMSTATUS_2011YES As String = "CHILDPROJECTFORMSTATUS_2011YES"
    Public Const CHILDPROJECTFORMSTATUS_2012YES As String = "CHILDPROJECTFORMSTATUS_2012YES"
    Public Const CHILDPROJECTFORMSTATUS_NO As String = "CHILDPROJECTFORMSTATUS_NO"
    Public Const CHILDPROJECTFORMSTATUS_NOTREQUIRED As String = "CHILDPROJECTFORMSTATUS_NOTREQUIRED"

    ' Child Project Subcategory
    Public Const CHILDPROJECTSUBCATEGORY_AIDSORPHANS As String = "CHILDPROJECTSUBCATEGORY_AIDSORPHANS"
    Public Const CHILDPROJECTSUBCATEGORY_ARMEDCONFLICTCHILDSOLDIERS As String = "CHILDPROJECTSUBCATEGORY_ARMEDCONFLICTCHILDSOLDIERS"
    Public Const CHILDPROJECTSUBCATEGORY_ARMEDCONFLICTREFUGEES As String = "CHILDPROJECTSUBCATEGORY_ARMEDCONFLICTREFUGEES"
    Public Const CHILDPROJECTSUBCATEGORY_CHILDSURVIVAL As String = "CHILDPROJECTSUBCATEGORY_CHILDSURVIVAL"
    Public Const CHILDPROJECTSUBCATEGORY_STREETSURVIVAL As String = "CHILDPROJECTSUBCATEGORY_STREETSURVIVAL"
    Public Const CHILDPROJECTSUBCATEGORY_TRAFFICKINGEXPLOITATIVELABOR As String = "CHILDPROJECTSUBCATEGORY_TRAFFICKINGEXPLOITATIVELABOR"
    Public Const CHILDPROJECTSUBCATEGORY_TRAFFICKINGSEXTRAFFICKING As String = "CHILDPROJECTSUBCATEGORY_TRAFFICKINGSEXTRAFFICKING"

    ' ChildLivesWith Values
    Public Const CHILDLIVESWITH_BOTHPARENTSATHOME As String = "CHILDLIVESWITH_BOTHPARENTSATHOME"
    Public Const CHILDLIVESWITH_DOESNOTLIVEWITHPARENTS As String = "CHILDLIVESWITH_DOESNOTLIVEWITHPARENTS"
    Public Const CHILDLIVESWITH_FATHERONLYATHOME As String = "CHILDLIVESWITH_FATHERONLYATHOME"
    Public Const CHILDLIVESWITH_MOTHERONLYATHOME As String = "CHILDLIVESWITH_MOTHERONLYATHOME"

    ' Child Father Works As values
    Public Const FATHERWORKSAS_BAKER As String = "FATHERWORKSAS_BAKER"
    Public Const FATHERWORKSAS_BUSINESSMAN As String = "FATHERWORKSAS_BUSINESSMAN"
    Public Const FATHERWORKSAS_COOK As String = "FATHERWORKSAS_COOK"
    Public Const FATHERWORKSAS_DAYLABORER As String = "FATHERWORKSAS_DAYLABORER"
    Public Const FATHERWORKSAS_DOMESTIC As String = "FATHERWORKSAS_DOMESTIC"
    Public Const FATHERWORKSAS_DRIVER As String = "FATHERWORKSAS_DRIVER"
    Public Const FATHERWORKSAS_FACTORYWORKER As String = "FATHERWORKSAS_FACTORYWORKER"
    Public Const FATHERWORKSAS_FARMER As String = "FATHERWORKSAS_FARMER"
    Public Const FATHERWORKSAS_FISHERMAN As String = "FATHERWORKSAS_FISHERMAN"
    Public Const FATHERWORKSAS_LABORER As String = "FATHERWORKSAS_LABORER"
    Public Const FATHERWORKSAS_MILLWORKER As String = "FATHERWORKSAS_MILLWORKER"
    Public Const FATHERWORKSAS_OFFICECLERK As String = "FATHERWORKSAS_OFFICECLERK"
    Public Const FATHERWORKSAS_OTHER As String = "FATHERWORKSAS_OTHER"
    Public Const FATHERWORKSAS_PASTOR As String = "FATHERWORKSAS_PASTOR"
    Public Const FATHERWORKSAS_PORTER As String = "FATHERWORKSAS_PORTER"
    Public Const FATHERWORKSAS_RETIRED As String = "FATHERWORKSAS_RETIRED"
    Public Const FATHERWORKSAS_RICKSHAWPULLER As String = "FATHERWORKSAS_RICKSHAWPULLER"
    Public Const FATHERWORKSAS_SECURITYGUARD As String = "FATHERWORKSAS_SECURITYGUARD"
    Public Const FATHERWORKSAS_SHOPKEEPER As String = "FATHERWORKSAS_SHOPKEEPER"
    Public Const FATHERWORKSAS_SOLDIER As String = "FATHERWORKSAS_SOLDIER"
    Public Const FATHERWORKSAS_SWEEPER As String = "FATHERWORKSAS_SWEEPER"
    Public Const FATHERWORKSAS_TAILOR As String = "FATHERWORKSAS_TAILOR"
    Public Const FATHERWORKSAS_TAXIDRIVER As String = "FATHERWORKSAS_TAXIDRIVER"
    Public Const FATHERWORKSAS_TEACHER As String = "FATHERWORKSAS_TEACHER"
    Public Const FATHERWORKSAS_UNEMPLOYED As String = "FATHERWORKSAS_UNEMPLOYED"
    Public Const FATHERWORKSAS_UNKNOWN As String = "FATHERWORKSAS_UNKNOWN"
    Public Const FATHERWORKSAS_VENDOR As String = "FATHERWORKSAS_VENDOR"

    'Child Mother Works As Values
    Public Const MOTHERWORKSAS_BAKER As String = "MOTHERWORKSAS_BAKER"
    Public Const MOTHERWORKSAS_BUSINESSWOMAN As String = "MOTHERWORKSAS_BUSINESSWOMAN"
    Public Const MOTHERWORKSAS_CIGARETTEROLLER As String = "MOTHERWORKSAS_CIGARETTEROLLER"
    Public Const MOTHERWORKSAS_COOK As String = "MOTHERWORKSAS_COOK"
    Public Const MOTHERWORKSAS_DAYLABORER As String = "MOTHERWORKSAS_DAYLABORER"
    Public Const MOTHERWORKSAS_DOMESTIC As String = "MOTHERWORKSAS_DOMESTIC"
    Public Const MOTHERWORKSAS_DRIVER As String = "MOTHERWORKSAS_DRIVER"
    Public Const MOTHERWORKSAS_FACTORYWORKER As String = "MOTHERWORKSAS_FACTORYWORKER"
    Public Const MOTHERWORKSAS_FARMERGARDNER As String = "MOTHERWORKSAS_FARMERGARDNER"
    Public Const MOTHERWORKSAS_HAIRSTYLIST As String = "MOTHERWORKSAS_HAIRSTYLIST"
    Public Const MOTHERWORKSAS_LABORER As String = "MOTHERWORKSAS_LABORER"
    Public Const MOTHERWORKSAS_LAUNDRY As String = "MOTHERWORKSAS_LAUNDRY"
    Public Const MOTHERWORKSAS_MAIDCLEANING As String = "MOTHERWORKSAS_MAIDCLEANING"
    Public Const MOTHERWORKSAS_NONEHOUSEWIFE As String = "MOTHERWORKSAS_NONEHOUSEWIFE"
    Public Const MOTHERWORKSAS_NURSE As String = "MOTHERWORKSAS_NURSE"
    Public Const MOTHERWORKSAS_OFFICECLERK As String = "MOTHERWORKSAS_OFFICECLERK"
    Public Const MOTHERWORKSAS_OTHER As String = "MOTHERWORKSAS_OTHER"
    Public Const MOTHERWORKSAS_PASTOR As String = "MOTHERWORKSAS_PASTOR"
    Public Const MOTHERWORKSAS_PORTER As String = "MOTHERWORKSAS_PORTER"
    Public Const MOTHERWORKSAS_RETIRED As String = "MOTHERWORKSAS_RETIRED"
    Public Const MOTHERWORKSAS_RICKSHAWPULLER As String = "MOTHERWORKSAS_RICKSHAWPULLER"
    Public Const MOTHERWORKSAS_SEAMSTRESS As String = "MOTHERWORKSAS_SEAMSTRESS"
    Public Const MOTHERWORKSAS_SECURITYGUARD As String = "MOTHERWORKSAS_SECURITYGUARD"
    Public Const MOTHERWORKSAS_SHOPKEEPER As String = "MOTHERWORKSAS_SHOPKEEPER"
    Public Const MOTHERWORKSAS_STREETVENDOR As String = "MOTHERWORKSAS_STREETVENDOR"
    Public Const MOTHERWORKSAS_SWEEPER As String = "MOTHERWORKSAS_SWEEPER"
    Public Const MOTHERWORKSAS_TAXIDRIVER As String = "MOTHERWORKSAS_TAXIDRIVER"
    Public Const MOTHERWORKSAS_TEACHER As String = "MOTHERWORKSAS_TEACHER"
    Public Const MOTHERWORKSAS_UNEMPLOYED As String = "MOTHERWORKSAS_UNEMPLOYED"
    Public Const MOTHERWORKSAS_UNKNOWN As String = "MOTHERWORKSAS_UNKNOWN"

    'Child Caregiver Relation Values
    Public Const CAREGIVERRELATION_AUNT As String = "CAREGIVERRELATION_AUNT"
    Public Const CAREGIVERRELATION_CARETAKER As String = "CAREGIVERRELATION_CARETAKER"
    Public Const CAREGIVERRELATION_GRANDFATHER As String = "CAREGIVERRELATION_GRANDFATHER"
    Public Const CAREGIVERRELATION_GRANDMOTHER As String = "CAREGIVERRELATION_GRANDMOTHER"
    Public Const CAREGIVERRELATION_GRANDPARENTS As String = "CAREGIVERRELATION_GRANDPARENTS"
    Public Const CAREGIVERRELATION_OTHER As String = "CAREGIVERRELATION_OTHER"
    Public Const CAREGIVERRELATION_PROJECTWORKER As String = "CAREGIVERRELATION_PROJECTWORKER"
    Public Const CAREGIVERRELATION_SIBLING As String = "CAREGIVERRELATION_SIBLING"
    Public Const CAREGIVERRELATION_UNCLE As String = "CAREGIVERRELATION_UNCLE"
    Public Const CAREGIVERRELATION_UNKNOWN As String = "CAREGIVERRELATION_UNKNOWN"
    Public Const CAREGIVERREASON_ABANDONED As String = "CAREGIVERREASON_ABANDONED"
    Public Const CAREGIVERREASON_MEMPHISTESTING As String = "CAREGIVERREASON_MEMPHISTESTING"
    Public Const CAREGIVERREASON_ORPHANED As String = "CAREGIVERREASON_ORPHANED"
    Public Const CAREGIVERREASON_OTHER As String = "CAREGIVERREASON_OTHER"
    Public Const CAREGIVERREASON_TESTCODE As String = "CAREGIVERREASON_TESTCODE"
    Public Const CAREGIVERREASON_TESTCODE2 As String = "CAREGIVERREASON_TESTCODE2"
    Public Const CAREGIVERREASON_UNKOWN As String = "CAREGIVERREASON_UNKOWN"

    ' Child Caregiver Works As Values
    Public Const CAREGIVERWORKSAS_BAKER As String = "CAREGIVERWORKSAS_BAKER"
    Public Const CAREGIVERWORKSAS_OTHER As String = "CAREGIVERWORKSAS_OTHER"

    ' Child Birthdate Accuracy
    Public Const BIRTHDATEACCURACY_ACTUAL As String = "BIRTHDATEACCURACY_ACTUAL"
    Public Const BIRTHDATEACCURACY_ESTIMATED As String = "BIRTHDATEACCURACY_ESTIMATED"

    ' Child Highest Class Level
    Public Const CHILDCLASSLEVEL_APPRENTICESHIP As String = "CHILDCLASSLEVEL_APPRENTICESHIP"
    Public Const CHILDCLASSLEVEL_KINDERGARTEN As String = "CHILDCLASSLEVEL_KINDERGARTEN"
    Public Const CHILDCLASSLEVEL_MIDDLESCHOOL6 As String = "CHILDCLASSLEVEL_MIDDLESCHOOL6"
    Public Const CHILDCLASSLEVEL_MIDDLESCHOOL7 As String = "CHILDCLASSLEVEL_MIDDLESCHOOL7"
    Public Const CHILDCLASSLEVEL_MIDDLESCHOOL8 As String = "CHILDCLASSLEVEL_MIDDLESCHOOL8"
    Public Const CHILDCLASSLEVEL_OTHER As String = "CHILDCLASSLEVEL_OTHER"
    Public Const CHILDCLASSLEVEL_PRESCHOOL As String = "CHILDCLASSLEVEL_PRESCHOOL"
    Public Const CHILDCLASSLEVEL_PRIMARY1 As String = "CHILDCLASSLEVEL_PRIMARY1"
    Public Const CHILDCLASSLEVEL_PRIMARY2 As String = "CHILDCLASSLEVEL_PRIMARY2"
    Public Const CHILDCLASSLEVEL_PRIMARY3 As String = "CHILDCLASSLEVEL_PRIMARY3"
    Public Const CHILDCLASSLEVEL_PRIMARY4 As String = "CHILDCLASSLEVEL_PRIMARY4"
    Public Const CHILDCLASSLEVEL_PRIMARY5 As String = "CHILDCLASSLEVEL_PRIMARY5"
    Public Const CHILDCLASSLEVEL_SECONDARY1 As String = "CHILDCLASSLEVEL_SECONDARY1"
    Public Const CHILDCLASSLEVEL_SECONDARY2 As String = "CHILDCLASSLEVEL_SECONDARY2"
    Public Const CHILDCLASSLEVEL_SECONDARY3 As String = "CHILDCLASSLEVEL_SECONDARY3"
    Public Const CHILDCLASSLEVEL_SECONDARY4 As String = "CHILDCLASSLEVEL_SECONDARY4"
    Public Const CHILDCLASSLEVEL_VOCATIONALSCHOOL As String = "CHILDCLASSLEVEL_VOCATIONALSCHOOL"

    ' Departure Administrative code values
    Public Const DEPARTURE_ADMINISTRATIVE_ADMINDUPLICATERECORD As String = "DEPARTURE_ADMINISTRATIVE_ADMINDUPLICATERECORD"
    Public Const DEPARTURE_ADMINISTRATIVE_ADMINFIELDMEMODELINQUENCY As String = "DEPARTURE_ADMINISTRATIVE_ADMINFIELDMEMODELINQUENCY"
    Public Const DEPARTURE_ADMINISTRATIVE_ADMINOTHER As String = "DEPARTURE_ADMINISTRATIVE_ADMINOTHER"
    Public Const DEPARTURE_ADMINISTRATIVE_ADMINPHASINGOUT As String = "DEPARTURE_ADMINISTRATIVE_ADMINPHASINGOUT"
    Public Const DEPARTURE_ADMINISTRATIVE_ADMINPROJECTCLOSED As String = "DEPARTURE_ADMINISTRATIVE_ADMINPROJECTCLOSED"

    ' Child Name Suffix
    Public Const CHILDNAMESUFFIX_I As String = "CHILDNAMESUFFIX_I"
    Public Const CHILDNAMESUFFIX_II As String = "CHILDNAMESUFFIX_II"
    Public Const CHILDNAMESUFFIX_III As String = "CHILDNAMESUFFIX_III"
    Public Const CHILDNAMESUFFIX_IV As String = "CHILDNAMESUFFIX_IV"
    Public Const CHILDNAMESUFFIX_V As String = "CHILDNAMESUFFIX_V"
    Public Const CHILDNAMESUFFIX_VI As String = "CHILDNAMESUFFIX_VI"

    ' Child Profile Status
    Public Const CHILDPROFILESTATUS_CONSIGNED As String = "CHILDPROFILESTATUS_CONSIGNED"
    Public Const CHILDPROFILESTATUS_CREATED As String = "CHILDPROFILESTATUS_CREATED"
    Public Const CHILDPROFILESTATUS_DONE As String = "CHILDPROFILESTATUS_DONE"
    Public Const CHILDPROFILESTATUS_SPNREADY As String = "CHILDPROFILESTATUS_SPNREADY"

    ' Child Profile Update
    Public Const CHILDPROFILEUPDATE_2006CCHFORM As String = "CHILDPROFILEUPDATE_2006CCHFORM"
    Public Const CHILDPROFILEUPDATE_2007CCHFORM As String = "CHILDPROFILEUPDATE_2007CCHFORM"
    Public Const CHILDPROFILEUPDATE_2008CCHFORM As String = "CHILDPROFILEUPDATE_2008CCHFORM"
    Public Const CHILDPROFILEUPDATE_2009CCHFORM As String = "CHILDPROFILEUPDATE_2009CCHFORM"
    Public Const CHILDPROFILEUPDATE_2010CCHFORM As String = "CHILDPROFILEUPDATE_2010CCHFORM"
    Public Const CHILDPROFILEUPDATE_2011CCHFORM As String = "CHILDPROFILEUPDATE_2011CCHFORM"
    Public Const CHILDPROFILEUPDATE_2012BPR As String = "CHILDPROFILEUPDATE_2012BPR"
    Public Const CHILDPROFILEUPDATE_2012CCHFORM As String = "CHILDPROFILEUPDATE_2012CCHFORM"
    Public Const CHILDPROFILEUPDATE_2012HWLETTER As String = "CHILDPROFILEUPDATE_2012HWLETTER"
    Public Const SPONSORSHIPPERFORMANCE_GOOD As String = "SPONSORSHIPPERFORMANCE_GOOD"
    Public Const SPONSORSHIPPERFORMANCE_POOR As String = "SPONSORSHIPPERFORMANCE_POOR"

    ' Interaction Extension Letter Type
    Public Const INTERACTIONEXTENSIONLETTERTYPE_CONTACTED As String = "INTERACTIONEXTENSIONLETTERTYPE_CONTACTED"
    Public Const INTERACTIONEXTENSIONLETTERTYPE_NOTCONTACTED As String = "INTERACTIONEXTENSIONLETTERTYPE_NOTCONTACTED"
    
    ' Interaction Extension Letter Child Version
    Public Const INTERACTIONEXTENSIONLETTERCHILDVERSION_MULTIPLECHILDRENLETTER As String = "INTERACTIONEXTENSIONLETTERCHILDVERSION_MULTIPLECHILDRENLETTER"
    Public Const INTERACTIONEXTENSIONLETTERCHILDVERSION_ONECHILDLETTER As String = "INTERACTIONEXTENSIONLETTERCHILDVERSION_ONECHILDLETTER"
    Public Const INTERACTIONEXTENSIONLETTERCHILDVERSION_TWOCHILDRENLETTER As String = "INTERACTIONEXTENSIONLETTERCHILDVERSION_TWOCHILDRENLETTER"


    ' Interaction Extension Fulfillment Status
    Public Const INTERACTIONEXTENSIONFULFILLMENTSTATUS_COMPLETE As String = "INTERACTIONEXTENSIONFULFILLMENTSTATUS_COMPLETE"
    Public Const INTERACTIONEXTENSIONFULFILLMENTSTATUS_PENDING As String = "INTERACTIONEXTENSIONFULFILLMENTSTATUS_PENDING"
    Public Const INTERACTIONEXTENSIONFULFILLMENTSTATUS_READY As String = "INTERACTIONEXTENSIONFULFILLMENTSTATUS_READY"


    ' Interaction Extension Departure Reason 
    Public Const INTERACTIONEXTENSIONDEPARTUREREASON_DR1DROPPEDOUT As String = "INTERACTIONEXTENSIONDEPARTUREREASON_DR1DROPPEDOUT"
    Public Const INTERACTIONEXTENSIONDEPARTUREREASON_DR10CHILDPREGNANT As String = "INTERACTIONEXTENSIONDEPARTUREREASON_DR10CHILDPREGNANT"
    Public Const INTERACTIONEXTENSIONDEPARTUREREASON_DR11NOLONGERATTENDING As String = "INTERACTIONEXTENSIONDEPARTUREREASON_DR11NOLONGERATTENDING"
    Public Const INTERACTIONEXTENSIONDEPARTUREREASON_DR12TAKENOUTBYCAREGIVER As String = "INTERACTIONEXTENSIONDEPARTUREREASON_DR12TAKENOUTBYCAREGIVER"
    Public Const INTERACTIONEXTENSIONDEPARTUREREASON_DR13FAMILYMOVED As String = "INTERACTIONEXTENSIONDEPARTUREREASON_DR13FAMILYMOVED"
    Public Const INTERACTIONEXTENSIONDEPARTUREREASON_DR14ABLETOPROVIDE As String = "INTERACTIONEXTENSIONDEPARTUREREASON_DR14ABLETOPROVIDE"
    Public Const INTERACTIONEXTENSIONDEPARTUREREASON_DR15HOMETOOFAR As String = "INTERACTIONEXTENSIONDEPARTUREREASON_DR15HOMETOOFAR"
    Public Const INTERACTIONEXTENSIONDEPARTUREREASON_DR2FAILEDSCHOOL As String = "INTERACTIONEXTENSIONDEPARTUREREASON_DR2FAILEDSCHOOL"
    Public Const INTERACTIONEXTENSIONDEPARTUREREASON_DR3LIVEWRELATIVES As String = "INTERACTIONEXTENSIONDEPARTUREREASON_DR3LIVEWRELATIVES"
    Public Const INTERACTIONEXTENSIONDEPARTUREREASON_DR4HEALTHPROBLEMS As String = "INTERACTIONEXTENSIONDEPARTUREREASON_DR4HEALTHPROBLEMS"
    Public Const INTERACTIONEXTENSIONDEPARTUREREASON_DR5POSTSECONDARYSCHOOL As String = "INTERACTIONEXTENSIONDEPARTUREREASON_DR5POSTSECONDARYSCHOOL"
    Public Const INTERACTIONEXTENSIONDEPARTUREREASON_DR6TRANSFERREDSCHOOLS As String = "INTERACTIONEXTENSIONDEPARTUREREASON_DR6TRANSFERREDSCHOOLS"
    Public Const INTERACTIONEXTENSIONDEPARTUREREASON_DR7CHILDEMPLOYED As String = "INTERACTIONEXTENSIONDEPARTUREREASON_DR7CHILDEMPLOYED"
    Public Const INTERACTIONEXTENSIONDEPARTUREREASON_DR8CHILDMARRIED As String = "INTERACTIONEXTENSIONDEPARTUREREASON_DR8CHILDMARRIED"
    Public Const INTERACTIONEXTENSIONDEPARTUREREASON_DR9NEEDEDATHOME As String = "INTERACTIONEXTENSIONDEPARTUREREASON_DR9NEEDEDATHOME"

    ' Interaction Extension UI Model Field Manager
    Public Const INTERACTIONEXTENSIONUIMODELFIELD_CHILDCOUNTLETTERVERSIONCODEID As String = "INTERACTIONEXTENSIONUIMODELFIELD_CHILDCOUNTLETTERVERSIONCODEID"
    Public Const INTERACTIONEXTENSIONUIMODELFIELD_CHILDREN As String = "INTERACTIONEXTENSIONUIMODELFIELD_CHILDREN"
    Public Const INTERACTIONEXTENSIONUIMODELFIELD_DEPARTEDCHILDID As String = "INTERACTIONEXTENSIONUIMODELFIELD_DEPARTEDCHILDID"
    Public Const INTERACTIONEXTENSIONUIMODELFIELD_DEPARTUREREASONCODEID As String = "INTERACTIONEXTENSIONUIMODELFIELD_DEPARTUREREASONCODEID"
    Public Const INTERACTIONEXTENSIONUIMODELFIELD_DOUBLESPONSOREDCHILDID As String = "INTERACTIONEXTENSIONUIMODELFIELD_DOUBLESPONSOREDCHILDID"
    Public Const INTERACTIONEXTENSIONUIMODELFIELD_EFTBROCHURECODE As String = "INTERACTIONEXTENSIONUIMODELFIELD_EFTBROCHURECODE"
    Public Const INTERACTIONEXTENSIONUIMODELFIELD_FULFILLMENTSTATUSCODEID As String = "INTERACTIONEXTENSIONUIMODELFIELD_FULFILLMENTSTATUSCODEID"
    Public Const INTERACTIONEXTENSIONUIMODELFIELD_LETTERTYPECODEID As String = "INTERACTIONEXTENSIONUIMODELFIELD_LETTERTYPECODEID"
    Public Const INTERACTIONEXTENSIONUIMODELFIELD_PREVIOUSBIRTHDATE As String = "INTERACTIONEXTENSIONUIMODELFIELD_PREVIOUSBIRTHDATE"
    Public Const INTERACTIONEXTENSIONUIMODELFIELD_PREVIOUSCHILDPROJECTID As String = "INTERACTIONEXTENSIONUIMODELFIELD_PREVIOUSCHILDPROJECTID"
    Public Const INTERACTIONEXTENSIONUIMODELFIELD_PREVIOUSNAME As String = "INTERACTIONEXTENSIONUIMODELFIELD_PREVIOUSNAME"
    Public Const INTERACTIONEXTENSIONUIMODELFIELD_RESENDCODE As String = "INTERACTIONEXTENSIONUIMODELFIELD_RESENDCODE"
    Public Const INTERACTIONEXTENSIONUIMODELFIELD_TRANSFERCHILDID As String = "INTERACTIONEXTENSIONUIMODELFIELD_TRANSFERCHILDID"
    Public Const INTERACTIONEXTENSIONUIMODELFIELD_UNAVAILABLECHILDID As String = "INTERACTIONEXTENSIONUIMODELFIELD_UNAVAILABLECHILDID"



End Class
