Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Bar code add data form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "1ca12f92-794b-4130-99bc-47bf8b04e909", "d8fb582e-9a10-4945-a044-2b3b15b13b52", "CRM child learning letter scanner add data form")> _
Partial Public Class [ChildLearningLetterLetterScannerAddDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

	Partial Private Sub OnCreated()
	End Sub

#End Region

	Private WithEvents _barcode As Global.Blackbaud.AppFx.UIModeling.Core.StringField
	Private WithEvents _barcodeelements As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of ChildLearningLetterLetterScannerAddDataFormBARCODEELEMENTSUIModel)
	Private WithEvents _submit As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
	Private WithEvents _scansession As Global.Blackbaud.AppFx.UIModeling.Core.StringField


	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public Sub New()
		MyBase.New()

		_barcode = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
		_barcodeelements = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of ChildLearningLetterLetterScannerAddDataFormBARCODEELEMENTSUIModel)
		_submit = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
		_scansession = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

		MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
		MyBase.DataFormTemplateId = New Guid("1ca12f92-794b-4130-99bc-47bf8b04e909")
		MyBase.DataFormInstanceId = New Guid("d8fb582e-9a10-4945-a044-2b3b15b13b52")
		MyBase.RecordType = "Bar Code"
		MyBase.FixedDialog = False
		MyBase.UserInterfaceUrl = "browser/htmlforms/custom/CRMChildLetterScannerAddDataForm.html"

		'
		'_barcode
		'
		_barcode.Name = "BARCODE"
		_barcode.Caption = "Bar code"
		_barcode.MaxLength = 100
		Me.Fields.Add(_barcode)
		'
		'_barcodeelements
		'
		_barcodeelements.Name = "BARCODEELEMENTS"
		_barcodeelements.Caption = "Results"
		_barcodeelements.AllowDelete = False
		_barcodeelements.EnablePaging = True
		_barcodeelements.ItemsPerPage = 18
		_barcodeelements.AllowColumnMove = True
		Me.Fields.Add(_barcodeelements)
		'
		'_submit
		'
		_submit.Name = "SUBMIT"
		_submit.Caption = "Save results"
		Me.Fields.Add(_submit)

		'
		'_scansession
		'
		_scansession.Caption = "Scan session"
		_scansession.Name = "SCANSESSION"
		_scansession.MaxLength = 100
		Me.Fields.Add(_scansession)

		OnCreated()

	End Sub

	''' <summary>
	''' Bar code (9-character string)
	''' </summary>
	<System.ComponentModel.Description("Bar code (9-character string)")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [BARCODE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
		Get
			Return _barcode
		End Get
	End Property

	''' <summary>
	''' Elements
	''' </summary>
	<System.ComponentModel.Description("Elements")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [BARCODEELEMENTS]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of ChildLearningLetterLetterScannerAddDataFormBARCODEELEMENTSUIModel)
		Get
			Return _barcodeelements
		End Get
	End Property

	''' <summary>
	''' Save results
	''' </summary>
	<System.ComponentModel.Description("Save results")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [SUBMIT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
		Get
			Return _submit
		End Get
	End Property


	''' <summary>
	''' Scan session
	''' </summary>
	<System.ComponentModel.Description("Scan session")> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
	Public ReadOnly Property [SCANSESSION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
		Get
			Return _scansession
		End Get
	End Property

End Class
